org.gradle.jvmargs=-Xmx6G
org.gradle.daemon=false

# Mod Info
mod_id=ldlib2
mod_name=LowDragLib2
mod_version=2.2.29-forge-1.20.1
mod_description=Low Drag Lib2, a library for rendering, gui, particles, synchronize
mod_license=LGPL-3.0 license
mod_url=https://github.com/Low-Drag-MC/LDLib2
mod_authors=KilaBash
mod_group_id=com.lowdragmc.ldlib2

# Minecraft / Forge
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.13
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=parchment
mapping_version=2023.09.03-1.20.1

# Libraries
kotlin_stdlib_version=2.1.20
kff_version=4.11.0
jei_version=15.20.0.133
rei_version=12.1.785
emi_version=1.1.22+1.20.1
ae2_version=15.3.4
kjs_version=2001.6.5-build.26
yoga_version=1.0.0
taffy_version=1.1.4
